#!/usr/bin/env node
// Joins the predecessor inventory (v1 provider methods) against the new endpoint inventory
// and dispositions every v1 entry: carried / renamed (old -> new) / retired (reason-coded).
// Writes provider-dev/config/predecessor_dispositions.csv and regenerates the Breaking
// Changes section of README.md between the BEGIN/END markers - the section is generated,
// never hand-written. Validate-and-fail-without-writing; no v1 entry may be undispositioned.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const cfg = (f) => join(repoRoot, 'provider-dev', 'config', f);
const readmePath = join(repoRoot, 'README.md');

const parseCsv = (text) => {
  const lines = text.trim().split('\n');
  const cols = lines[0].split(',');
  return lines.slice(1).map((line) => {
    const vals = [];
    let cur = '', inQ = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (inQ) {
        if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; }
        else if (ch === '"') inQ = false;
        else cur += ch;
      } else if (ch === '"') inQ = true;
      else if (ch === ',') { vals.push(cur); cur = ''; }
      else cur += ch;
    }
    vals.push(cur);
    return Object.fromEntries(cols.map((c, i) => [c, vals[i] ?? '']));
  });
};

const predecessors = parseCsv(readFileSync(cfg('predecessor_inventory.csv'), 'utf8'));
const inventory = parseCsv(readFileSync(cfg('endpoint_inventory.csv'), 'utf8'));
const filterReport = parseCsv(readFileSync(cfg('filter_report.csv'), 'utf8'));

// v1 services that are wholly the admin-key surface -> openai_admin sibling.
// Their operationIds were also renamed upstream, so the opId join cannot see them.
const ORG_SERVICES = new Set(['audit_logs', 'invites', 'projects', 'users']);

const camel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

const byOpId = new Map();
for (const r of inventory) byOpId.set(r.operation_id.toLowerCase(), r);
const filterByOpId = new Map();
for (const r of filterReport)
  for (const id of r.operation_ids.split(';').filter(Boolean)) filterByOpId.set(id.toLowerCase(), r.reason);

const errors = [];
const out = [];
for (const p of predecessors) {
  const oldFqn = `openai.${p.service}.${p.resource}`;
  const row = {
    service: p.service, resource: p.resource, method: p.method, verb: p.verb,
    old_fqn: oldFqn, disposition: '', new_fqn: '', new_method: '', reason: '',
  };
  if (ORG_SERVICES.has(p.service)) {
    row.disposition = 'retired';
    row.reason = 'org-admin-surface(openai_admin)';
    out.push(row);
    continue;
  }
  const opId = camel(p.method).toLowerCase();
  const inv = byOpId.get(opId);
  if (inv && !inv.skip_reason) {
    const newFqn = `openai.${inv.service}.${inv.resource}`;
    row.disposition = newFqn === oldFqn ? 'carried' : 'renamed';
    row.new_fqn = newFqn;
    row.new_method = inv.method;
    out.push(row);
    continue;
  }
  if (inv && inv.skip_reason) {
    row.disposition = 'retired';
    row.reason = inv.skip_reason;
    out.push(row);
    continue;
  }
  const filterReason = filterByOpId.get(opId);
  if (filterReason) {
    row.disposition = 'retired';
    row.reason = filterReason + (filterReason === 'org-admin-surface' ? '(openai_admin)' : '');
    out.push(row);
    continue;
  }
  errors.push(`${oldFqn}.${p.method}: no disposition (opId ${camel(p.method)} unmatched)`);
}

if (errors.length) {
  console.error(`FAIL: ${errors.length} undispositioned v1 entr(y/ies); nothing written`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

// README must carry the markers exactly once each
const readme = readFileSync(readmePath, 'utf8');
const BEGIN = '<!-- BEGIN:BREAKING-CHANGES (generated by disposition_predecessor.mjs - do not edit) -->';
const END = '<!-- END:BREAKING-CHANGES -->';
if (readme.split(BEGIN).length !== 2 || readme.split(END).length !== 2) {
  console.error('FAIL: README.md must contain exactly one BEGIN/END BREAKING-CHANGES marker pair; nothing written');
  process.exit(1);
}

// ---- write dispositions csv
const cols = ['service', 'resource', 'method', 'verb', 'old_fqn', 'disposition', 'new_fqn', 'new_method', 'reason'];
const csvEscape = (v) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);
writeFileSync(
  cfg('predecessor_dispositions.csv'),
  [cols.join(','), ...out.map((r) => cols.map((c) => csvEscape(r[c])).join(','))].join('\n') + '\n'
);

// ---- generate the Breaking Changes section
const carried = out.filter((r) => r.disposition === 'carried');
const renamed = out.filter((r) => r.disposition === 'renamed');
const retired = out.filter((r) => r.disposition === 'retired');

const resourceRenames = new Map();
for (const r of renamed) resourceRenames.set(r.old_fqn, r.new_fqn);
const methodRenames = [...carried, ...renamed].filter((r) => r.method !== r.new_method);

// a retired METHOD on a resource that otherwise survives is not a retired RESOURCE
const survivingFqns = new Set([...carried, ...renamed].map((r) => r.old_fqn));
const retiredWholeResource = retired.filter((r) => !survivingFqns.has(r.old_fqn));
const retiredMethodOnly = retired.filter((r) => survivingFqns.has(r.old_fqn));

const retiredByReason = new Map();
for (const r of retiredWholeResource) {
  if (!retiredByReason.has(r.reason)) retiredByReason.set(r.reason, []);
  retiredByReason.get(r.reason).push(r);
}
const REASON_TEXT = {
  'org-admin-surface(openai_admin)':
    'Organization/admin surface (separate admin key class) - moved to the sibling [`openai_admin`](https://github.com/stackql/stackql-provider-registry) provider',
  'data-plane-inference':
    'Inference invocation (data plane) - out of scope per the standing model-provider posture; use the vendor SDKs for invocation',
  'binary-transfer': 'Binary transfer - out of scope per the standing exclusions (metadata remains queryable)',
  'multipart-binary-body': 'Multipart binary upload body - not expressible; file content uploads are out of scope (metadata remains queryable)',
};

const fmtResourceSet = (rows) => {
  const set = [...new Set(rows.map((r) => `\`${r.old_fqn}\``))].sort();
  return set.join(', ');
};

const lines = [];
lines.push(BEGIN);
lines.push('');
lines.push('### Breaking Changes from the v1 Provider');
lines.push('');
lines.push('This rebuild replaces the published v1 `openai` provider. Every v1 resource is dispositioned below');
lines.push(`(generated from \`provider-dev/config/predecessor_dispositions.csv\`: ${out.length} v1 methods -> ${carried.length} carried, ${renamed.length} renamed, ${retired.length} retired).`);
lines.push('The old provider version remains available in the registry for pinning.');
lines.push('');
lines.push('**Renamed resources** (old -> new):');
lines.push('');
lines.push('| v1 resource | This rebuild |');
lines.push('|---|---|');
for (const [oldFqn, newFqn] of [...resourceRenames.entries()].sort()) lines.push(`| \`${oldFqn}\` | \`${newFqn}\` |`);
lines.push('');
lines.push('**Retired resources** (reason-coded):');
lines.push('');
for (const [reason, rows] of [...retiredByReason.entries()].sort()) {
  lines.push(`- ${REASON_TEXT[reason] || reason}: ${fmtResourceSet(rows)}`);
}
lines.push('');
if (retiredMethodOnly.length) {
  lines.push('**Retired methods on surviving resources**:');
  lines.push('');
  for (const r of retiredMethodOnly.sort((a, b) => a.old_fqn.localeCompare(b.old_fqn) || a.method.localeCompare(b.method))) {
    lines.push(`- \`${r.old_fqn}.${r.method}\` - ${REASON_TEXT[r.reason] || r.reason}`);
  }
  lines.push('');
}
lines.push('**Method naming** - v1 operation-derived method names become resource-scoped names');
lines.push('(`list_batches` -> `list`, `retrieve_batch` -> `get`, `create_fine_tuning_job` -> `create`, ...).');
lines.push(`${methodRenames.length} of the ${carried.length + renamed.length} surviving methods are renamed this way; the mapping is one-to-one per resource and recorded in the dispositions CSV.`);
lines.push('');
lines.push(END);

const newReadme = readme.slice(0, readme.indexOf(BEGIN)) + lines.join('\n') + readme.slice(readme.indexOf(END) + END.length);
writeFileSync(readmePath, newReadme);

console.log(`Dispositioned ${out.length} v1 methods -> ${cfg('predecessor_dispositions.csv')}`);
console.log(`  carried: ${carried.length}`);
console.log(`  renamed: ${renamed.length} (${resourceRenames.size} distinct resource renames)`);
console.log(`  retired: ${retired.length}`);
for (const [reason, rows] of [...retiredByReason.entries()].sort()) console.log(`    ${reason}: ${rows.length}`);
console.log('Breaking Changes section regenerated in README.md');
